package main;

public enum Jobs {
    INTERN("INTERN/APPRENTICE"),
    MUSICIAN("PERFORMER/MUSICIAN"),
    TRAVELLER("WORLD TRAVELLER"),
    POTATO("COUCH POTATO"),
    STUDENT("SUMMER STUDENT"),
    PICKER("FRUIT PICKER"),
    PARK("PROVINCIAL PARK EMPLOYEE"),
    FARM("FARM LABOURER"),
    PLANTER("TREE PLANTER"),
    LANDSCAPER("LANDSCAPER"),
    SALES("SALES CLERK"),
    MUSEUM("MUSEUM INTERPRETER"),
    CAMP("SUMMER CAMP LEADER"),
    ENTREPRENEUR("SMALL BUSINESS OWNER"),
    BUSKER("PERFORMER/BUSKER"),
    USRA("USRA RECIPIENT"),
    GOVERNMENT("CIVIL SERVANT"),
    ADMIN("ADMIN ASSISTANT/SECRETARY"),
    DEV("SOFTWARE DEVELOPER"),
    TUTOR("TUTOR"),
    RESEARCHER("RESEARCH ASSISTANT"),
    UNIVERSITY("MCMASTER OFFICE ASSISTANT"),
    BARTENDER("BARTENDER"),
    BARRISTA("BARRISTA"),
    FASTFOOD("FAST FOOD RESTAURANT EMPLOYEE"),
    COOK("PREP COOK/DISHWASHER"),
    GROCERY("GROCERY STORE EMPLOYEE"),
    SECURITY("SECURITY GUARD/ BOUNCER"),
    GUARD("LIFEGUARD"),
    REFEREE("SPORT REFEREE"),
    TEST_SUBJECT("MEDICAL TEST SUBJECT"),
    MARKETING("BRAND PROMOTER");
    
    private final String job;
    
    Jobs(String job) {
        this.job = job;
    }
    
    public String getFullJob() {
        return this.job;
    }
}
